"""Copy all web assets required for PWA + Capacitor Android into www/."""
from __future__ import annotations

import json
import hashlib
import re
import shutil
import sys
import time
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))

ROOT = Path(__file__).resolve().parents[1]
WWW = ROOT / "www"

VERSION_JSON_URL_BASE = "https://threecats-lsp.com/d-planner-plus"
DIRECT_APK_URL = (
    "https://raw.githubusercontent.com/Three-Cats-LSP/LSP_D-planner-plus/"
    "main/Android%20Apk/LSP_D-planner-plus.apk"
)
DIRECT_APK_FILE_NAME = "LSP_D-planner-plus.apk"

# Single files at repo root required for offline app + ZHL engine
ROOT_FILES = [
    "index.html",
    "app-version.js",
    "app-build.js",
    "capacitor-bridge.js",
    "android-select-picker.js",
    "manifest.json",
    "icon-192.png",
    "icon-512.png",
    "sw.js",
    "lsp-dplanner-foundation.css",
    "lsp-dplanner-modes.css",
    "lsp-dplanner-controls.css",
    "lsp-dplanner-results.css",
    "lsp-dplanner-mobile-shell.css",
    "zhl-engine-bundle.js",
    "padi-engine.js",
    "vpm-engine-bundle.js",
    "zhl-worker-bridge.js",
    "zhl-schedule-worker.js",
    "planner-inputs-core.js",
    "rec-planner.js",
    "settings-core.js",
    "surf-interval-core.js",
    "gas-table-core.js",
    "gas-plan-core.js",
    "gas-cards-core.js",
    "export-core.js",
    "dive-graph-engine.js",
    "plot-core.js",
    "gf-curve-core.js",
    "contingency-core.js",
    "results-panel.js",
    "results-render-core.js",
    "schedule-runner-core.js",
    "zhl-headless-adapter.js",
    "planner-shell.js",
]

# Directories copied recursively (vendor fonts, jsPDF, partner icons)
ROOT_DIRS = [
    "vendor",
]

RMTREE_RETRIES = 6
RMTREE_RETRY_DELAY_SECONDS = 0.5


def parse_app_version(app_version_js: str) -> str:
    match = re.search(r"APP_VERSION\s*=\s*['\"]([^'\"]+)['\"]", app_version_js)
    if not match:
        raise SystemExit("Could not parse APP_VERSION from app-version.js")
    return match.group(1)


def version_to_code(version: str) -> int:
    parts = version.split(".")
    if len(parts) != 3 or not all(p.isdigit() for p in parts):
        raise SystemExit(f"Invalid APP_VERSION format: {version}")
    major, minor, patch = (int(p) for p in parts)
    return major * 10000 + minor * 100 + patch


def write_version_json(version: str) -> None:
    build_id = compute_build_id()
    payload = {
        "version": version,
        "versionCode": version_to_code(version),
        "buildId": build_id,
        "apkUrl": DIRECT_APK_URL,
        "apkFileName": DIRECT_APK_FILE_NAME,
        "downloadPage": f"{VERSION_JSON_URL_BASE}/download.html",
    }
    text = json.dumps(payload, indent=2) + "\n"
    (ROOT / "version.json").write_text(text, encoding="utf-8", newline="\n")


def _build_fingerprint_asset_names() -> list[str]:
    excluded = {"app-build.js", "version.json"}
    return sorted(name for name in ROOT_FILES if name not in excluded)


def compute_build_id() -> str:
    digest = hashlib.sha256()
    for name in _build_fingerprint_asset_names():
        path = ROOT / name
        if not path.is_file():
            raise SystemExit(f"Missing required build fingerprint asset: {name}")
        digest.update(name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    for dirname in ROOT_DIRS:
        root_dir = ROOT / dirname
        if not root_dir.is_dir():
            raise SystemExit(f"Missing required build fingerprint directory: {dirname}")
        for path in sorted(p for p in root_dir.rglob("*") if p.is_file()):
            rel = path.relative_to(ROOT).as_posix()
            digest.update(rel.encode("utf-8"))
            digest.update(b"\0")
            digest.update(path.read_bytes())
            digest.update(b"\0")
    return digest.hexdigest()[:12]


def write_app_build_js(build_id: str | None = None) -> str:
    if build_id is None:
        build_id = compute_build_id()
    text = (
        "/**\n"
        " * App build fingerprint -- generated by tools/sync_www.py and tools/build_pages_site.py.\n"
        " * Changes whenever deployed runtime assets change, so the service worker cache refreshes\n"
        " * without requiring a manual APP_VERSION bump for every small UI fix.\n"
        " */\n"
        "(function (g) {\n"
        "  'use strict';\n"
        f"  g.APP_BUILD_ID = '{build_id}';\n"
        "})(typeof self !== 'undefined' ? self : globalThis);\n"
    )
    (ROOT / "app-build.js").write_text(text, encoding="utf-8", newline="\n")
    return build_id


def remove_tree_with_retries(path: Path) -> None:
    """Bound transient Windows file locks from recently closed Playwright servers."""
    last_error: OSError | None = None
    for attempt in range(RMTREE_RETRIES):
        try:
            shutil.rmtree(path)
            return
        except OSError as exc:
            last_error = exc
            if attempt == RMTREE_RETRIES - 1:
                break
            time.sleep(RMTREE_RETRY_DELAY_SECONDS)
    raise RuntimeError(f"Could not remove {path} after {RMTREE_RETRIES} attempts: {last_error}") from last_error


def sync_www() -> None:
    from update_sw_version import main as verify_app_version

    app_version_path = ROOT / "app-version.js"
    app_version = parse_app_version(app_version_path.read_text(encoding="utf-8"))
    build_id = write_app_build_js()
    write_version_json(app_version)
    verify_app_version()

    if WWW.exists():
        remove_tree_with_retries(WWW)
    WWW.mkdir(parents=True)

    for name in ROOT_FILES:
        src = ROOT / name
        if not src.is_file():
            raise SystemExit(f"Missing required web asset: {name}")
        dest = WWW / name
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)

    for name in ROOT_DIRS:
        src = ROOT / name
        if not src.is_dir():
            raise SystemExit(f"Missing required web directory: {name}")
        shutil.copytree(src, WWW / name, dirs_exist_ok=True)

    shutil.copy2(ROOT / "version.json", WWW / "version.json")

    print(f"Synced {len(ROOT_FILES)} files + {len(ROOT_DIRS)} dirs -> {WWW}")
    print(f"Wrote version.json for {app_version} build {build_id}")


if __name__ == "__main__":
    sync_www()
