"""Download and vendor offline assets (fonts, PDF fonts, partner icons)."""
from __future__ import annotations

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONTS_DIR = ROOT / "vendor" / "fonts"
ICONS_DIR = ROOT / "vendor" / "icons"
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

GOOGLE_CSS = (
    "https://fonts.googleapis.com/css2?"
    "family=Bebas+Neue&"
    "family=JetBrains+Mono:wght@300;400;500;700&"
    "family=Outfit:wght@300;400;500;600;700&"
    "display=swap"
)

DEJAVU = [
    (
        "https://cdn.jsdelivr.net/npm/dejavu-fonts-ttf@2.37.3/ttf/DejaVuSans.ttf",
        "DejaVuSans.ttf",
    ),
    (
        "https://cdn.jsdelivr.net/npm/dejavu-fonts-ttf@2.37.3/ttf/DejaVuSans-Bold.ttf",
        "DejaVuSans-Bold.ttf",
    ),
]

GIW_ICON = (
    "https://threecats-lsp.com/get-in-water/icon-192.png",
    "giw-icon-192.png",
)


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=120) as resp:
        return resp.read()


def vendor_google_fonts() -> list[str]:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    css = fetch(GOOGLE_CSS).decode("utf-8")
    local_css: list[str] = []
    precache: list[str] = []

    def repl(match: re.Match) -> str:
        url = match.group(1)
        name = url.split("/")[-1].split("?")[0]
        dest = FONTS_DIR / name
        if not dest.exists() or dest.stat().st_size == 0:
            dest.write_bytes(fetch(url))
            print(f"  downloaded {name}")
        rel = f"vendor/fonts/{name}"
        precache.append(rel)
        return f"url('{name}')"

    rewritten = re.sub(r"url\((https://[^)]+\.woff2[^)]*)\)", repl, css)
    # Normalize to single @font-face blocks (strip unused unicode-range duplicates for simplicity)
    out_path = FONTS_DIR / "fonts.css"
    header = "/* Self-hosted UI fonts — generated by tools/vendor_offline_assets.py */\n"
    out_path.write_text(header + rewritten, encoding="utf-8")
    local_css.append("vendor/fonts/fonts.css")
    precache.append("vendor/fonts/fonts.css")
    return precache


def vendor_dejavu() -> list[str]:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    paths = []
    for url, fname in DEJAVU:
        dest = FONTS_DIR / fname
        if not dest.exists() or dest.stat().st_size == 0:
            dest.write_bytes(fetch(url))
            print(f"  downloaded {fname}")
        paths.append(f"vendor/fonts/{fname}")
    return paths


def vendor_giw_icon() -> str | None:
    ICONS_DIR.mkdir(parents=True, exist_ok=True)
    url, fname = GIW_ICON
    dest = ICONS_DIR / fname
    try:
        if not dest.exists() or dest.stat().st_size == 0:
            dest.write_bytes(fetch(url))
            print(f"  downloaded {fname}")
        return f"vendor/icons/{fname}"
    except Exception as exc:
        print(f"  WARN: could not fetch GIW icon: {exc}")
        return None


def main() -> None:
    print("Vendoring Google Fonts...")
    gf = vendor_google_fonts()
    print("Vendoring DejaVu PDF fonts...")
    dv = vendor_dejavu()
    print("Vendoring Get In Water icon...")
    giw = vendor_giw_icon()

    manifest = ROOT / "vendor" / "offline-manifest.txt"
    lines = sorted(set(gf + dv + ([giw] if giw else [])))
    manifest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {manifest} ({len(lines)} assets)")


if __name__ == "__main__":
    main()
